server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://172.20.2.183:3306/labsys?characterEncoding=UTF-8
    username: zhp
    password: zhp
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: none
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  jackson:
    time-zone: "GMT+08"